/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package src.main.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Gender { 
  male, female  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Gender\",\"namespace\":\"src.main.avro\",\"symbols\":[\"male\",\"female\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
