/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package src.main.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Programs { 
  HighQuality, Honors  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Programs\",\"namespace\":\"src.main.avro\",\"symbols\":[\"HighQuality\",\"Honors\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
